# Generated by Django 6.1 on 2026-09-02 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('data_criacao_reserva', models.DateTimeField(auto_now_add=True)),
                ('imovel_reservado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imovel_reservado', to='listings.imovel')),
                ('usuario_inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquilino', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
