# Generated by Django 6.1 on 2026-09-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_reserva_status_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
