# Generated by Django 6.1 on 2026-09-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_reserva_valor_diaria_reserva_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status_reserva',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluida')], default='pendente', max_length=20),
        ),
    ]
