# Generated by Django 6.1 on 2026-08-31 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_hospedes', models.PositiveIntegerField()),
                ('publicado', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('anfitriao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
