# Generated by Django 6.1 on 2026-09-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImovelFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis_fotos/')),
                ('Imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='listings.imovel')),
            ],
        ),
    ]
