# Generated by Django 6.1 on 2026-09-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_imovelfoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovelfoto',
            old_name='Imovel',
            new_name='imovel',
        ),
    ]
